version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - '55432:5432'
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
volumes:
  db:
    driver: local